version: '3.8'

services:
  veyra-db:
    image: postgres:15-alpine
    container_name: veyra-postgres
    restart: always
    environment:
      POSTGRES_USER: veyra_user
      POSTGRES_PASSWORD: veyra_password
      POSTGRES_DB: veyra_production_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
